### ISSUE TITLE
Failed to mine after ... after network upgrade

### ISSUE THREAD

**Issue by reb0rn21** [hemilabs/heminetwork#89]
### Confirmation

- [X] I have checked for similar issues.

### Describe the bug

I today updated and compiled latest version as after the network upgrade older version produced errors but now with current/latest one i see only this with the pop miner:

`2024-04-18 19:03:36 INFO popm popm.go:494 Received keystone for mining with height 446350...
2024-04-18 19:03:36 INFO popm popm.go:294 Broadcasting PoP transaction to Bitcoin...
2024-04-18 19:03:36 ERROR popm popm.go:498 Failed to mine keystone: broadcast PoP transaction:  [7ffe6a72476d3200:1713467016]
2024-04-18 19:03:36 INFO popm popm.go:494 Received keystone for mining with height 446325...
2024-04-18 19:03:36 INFO popm popm.go:294 Broadcasting PoP transaction to Bitcoin...`

### Expected behaviour

to work

### Environment

Version: Hemi Proof of Proof miner: v0.1.0-pre+ca22d9c73
Operating System: Ubuntu 22.04
Architecture: amd64

**Comment by ClaytonNorthey92** [comment]
thanks for opening this @reb0rn21 , looking into it

**Comment by max-sanchez** [comment]
@reb0rn21 Hey! It appears this issue is actually due to recent fee spikes, can you compile the code from here and see if it fixes your issue? https://github.com/hemilabs/heminetwork/pull/91

You'll need to run it with the additional environment variable POPM_STATIC_FEE, which sets the fee-per-vB for the PoP transactions. You'll need to set to something that's in-line with the current network fees, I tested it with POPM_STATIC_FEE=25. The Bitcoin network's mempool has a lot of entries and is not allowing min-fee txs to propagate. [mempool.space/testnet](https://mempool.space/testnet) is a great place to look at current fee levels.

Eventually this will be made dynamic and BFG will have an RPC command to get current fee levels.

**Comment by reb0rn21** [comment]
Works now
tnx

**Comment by joshuasing** [comment]
Thanks for reporting this issue! I believe this was resolved by #91.
Please reopen this issue if it becomes a problem again.
